### ISSUE TITLE
Warning: SoapClient::__doRequest(): SSL: Se ha forzado la interrupción de una conexión existente por el host remoto.

### ISSUE THREAD

**Issue by achapiroppm** [TodoPago/SDK-PHP#87]
# SDK-PHP | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [X ] ¿Habilitaste la extensión SOAP de PHP?
* [X ] ¿Habilitaste la extensión CURL de PHP?
* [X] ¿Habilitaste la extensión openSSL de PHP?
* [X ] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/dev-sdk-php/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Redireccion a todopago para realizar el pago 

## Comportamiento actual
> Se genera el siguiente error:

Warning: SoapClient::__doRequest(): SSL: Se ha forzado la interrupción de una conexión existente por el host remoto. in C:\laragon\www\SDK-PHP\TodoPago\lib\Sdk.php on line 192

Fatal error: Uncaught SoapFault exception: [HTTP] Error Fetching http headers in C:\laragon\www\SDK-PHP\TodoPago\lib\Sdk.php:192 Stack trace: #0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'https://develop...', '', 1, 0) #1 C:\laragon\www\SDK-PHP\TodoPago\lib\Sdk.php(192): SoapClient->__call('SendAuthorizeRe...', Array) #2 C:\laragon\www\SDK-PHP\TodoPago\lib\Sdk.php(114): TodoPago\Sdk->getAuthorizeRequestResponse(Object(stdClass)) #3 C:\laragon\www\SDK-PHP\resources\ejemplo_2\index.php(50): TodoPago\Sdk->sendAuthorizeRequest(Array, Array) #4 {main} thrown in C:\laragon\www\SDK-PHP\TodoPago\lib\Sdk.php on line 192

## Pasos a reproducir
> Simplemente estoy ejecuntando el ejemplo_2 del SDK y no funciona, ya lo tenia andando en un desarrollo de un e-commerce pero al querer mostrarle al cliente el checkout dejo de funcionar.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO: LINUX 
  * __Servidor Web y versión: APACHE 2
  * __Versión de PHP: 7.4.2 https://latindevs.com/info.php
  * __Versión de SDK: V1.10.2
  * __Ambiente de Todopago: test

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.

**Comment by achapiroppm** [comment]
Adjunto el código que estoy ejecutando:

 // ************* PAGOS CON TARJETAS ***************
            
            //datos constantes
            define('SECURITY', 'TODOPAGO E571136DB760223552740B958A4B342D'); //API Keys sin PRISMA o TODOPAGO y sin espacio.
            define('CURRENCYCODE', 032);
            define('ENCODINGMETHOD', 'XML');
            define('MERCHANT', 1496056);
            define('KEY','TODOPAGO E571136DB760223552740B958A4B342D'); 
            $mode = "test";
            
            $http_header = array('Authorization'=>KEY);//authorization key del ambiente requerido
            
            
            //id de la operacion
            $operationid = rand(0, 99999999);

            //opciones para el método sendAuthorizeRequest (datos propios del comercio)
            $optionsSAR_comercio = array (
                'Security'=> SECURITY,
                'EncodingMethod'=>ENCODINGMETHOD,
                'Merchant'=>MERCHANT,
                'URL_OK'=>"http://".$_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT'].str_replace ($_SERVER['DOCUMENT_ROOT'], '', dirname($_SERVER['SCRIPT_FILENAME']))."/cart/exito?operationid=$operationid",
                'URL_ERROR'=>"http://".$_SERVER['SERVER_NAME'].":".$_SERVER['SERVER_PORT'].str_replace ($_SERVER['DOCUMENT_ROOT'], '', dirname($_SERVER['SCRIPT_FILENAME']))."/cart/error?operationid=$operationid",
                // 'END_POINT' => "https://developers.todopago.com.ar/services/t/1.1/",
                // 'Authorize' => "https://developers.todopago.com.ar/services/t/1.1/Authorize?wsdl",
                // 'PaymentMethods' => "https://developers.todopago.com.ar/services/t/1.1/PaymentMethods?wsdl",
                // 'Operations' => "https://developers.todopago.com.ar/services/t/1.1/Operations?wsdl",
            );

            // + opciones para el método sendAuthorizeRequest (datos propios de la operación) 
            //echo $this->input->ip_address();
            $optionsSAR_operacion=array(
                        'MERCHANT'=>MERCHANT,
                        'OPERATIONID'=> $operationid,
                        'CURRENCYCODE'=> CURRENCYCODE,
                        'AMOUNT'=>$_POST['amount'],                        
                        'MININSTALLMENTS'=>$_POST['cuotas'],
	                    'MAXINSTALLMENTS'=>$_POST['cuotas'],
                        'EMAILCLIENTE'=>$_POST['CSBTEMAIL'],   
                        'CSBTCITY'=>'Buenos Aires',   
                        'CSBTCOUNTRY'=>'AR',
                        'CSBTCUSTOMERID'=>$_POST['CSBTCUSTOMERID'],
                        'CSBTIPADDRESS'=> $this->input->ip_address(),
                        'CSBTEMAIL'=>'ventas@lanware.com.ar',
                        'CSBTFIRSTNAME'=>$_POST['CSBTFIRSTNAME'],
                        'CSBTLASTNAME'=>$_POST['CSBTLASTNAME'],
                        'CSBTPHONENUMBER'=>$_POST['CSBTPHONENUMBER'],    
                        'CSBTPOSTALCODE'=>$_POST['CSBTPOSTALCODE'],
                        'CSBTSTATE'=>$_POST['CSBTSTATE'],
                        'CSBTSTREET1'=>$_POST['CSBTSTREET1'],
                        'CSBTSTREET2'=>$_POST['CSBTSTREET2'],
                        'CSPTCURRENCY'=>$_POST['CSPTCURRENCY'],
                        'CSPTGRANDTOTALAMOUNT'=>$_POST['amount'],                        
                        'CSSTCITY'=>$_POST['CSSTCITY'], 
                        'CSSTCOUNTRY'=>$_POST['CSSTCOUNTRY'],
                        'CSSTEMAIL'=>$_POST['CSBTEMAIL'],
                        'CSSTFIRSTNAME'=>$_POST['CSSTFIRSTNAME'],
                        'CSSTLASTNAME'=>$_POST['CSSTLASTNAME'],
                        'CSSTPHONENUMBER'=>$_POST['CSSTPHONENUMBER'],
                        'CSSTPOSTALCODE'=>$_POST['CSBTPOSTALCODE'],
                        'CSSTSTATE'=>$_POST['CSSTSTATE'],
                        'CSSTSTREET1'=>$_POST['CSSTSTREET1'],
                        /* 'CSMDD12'=>$_POST['CSMDD12'],
                        'CSMDD13'=>$_POST['CSMDD13'],
                        'CSMDD14'=>$_POST['CSMDD14'],
                        'CSMDD15'=>$_POST['CSMDD15'],
                        'CSMDD16'=>$_POST['CSMDD16'], */
                        'CSITPRODUCTCODE'=>$_POST['CSITPRODUCTCODE'],                        
                        'CSITPRODUCTDESCRIPTION'=>$_POST['CSITPRODUCTDESCRIPTION'],                        
                        'CSITPRODUCTNAME'=>$_POST['CSITPRODUCTNAME'],
                        'CSITPRODUCTSKU'=>$_POST['CSITPRODUCTSKU'],
                        'CSITTOTALAMOUNT'=>$_POST['amount'],
                        'CSITQUANTITY'=>1,
                        'CSITUNITPRICE'=>$_POST['amount'], 
                        /* 'URL_OK'=>$_POST['URL_OK'],
                        'URL_ERROR'=>$_POST['URL_ERROR'], */
                
                    );    
                    //dumpeo($optionsSAR_operacion); exit;
            
            $this->session->set_userdata('operacion',$optionsSAR_operacion);
            
            //creo instancia de la clase TodoPago
            $connector = new TodoPago\Sdk($http_header, $mode);
            
            $rta = $connector->sendAuthorizeRequest($optionsSAR_comercio, $optionsSAR_operacion);
            
           //dumpeo($rta);
            if($rta['StatusCode'] != -1) {
                dumpeo($rta);
            } else {
                setcookie('RequestKey',$rta["RequestKey"],  time() + (86400 * 30), "/");
                header("Location: ".$rta["URL_Request"]);		
            }

**Comment by achapiroppm** [comment]
Buenos días, 
Mi servidor está en el hosting mochahost.com (dominio latindevs.com).
Se podría chequear también el site a donde va a correr en producción, el dominio es lanware.com.ar que reside en dreamhost.com.

Muchas gracias!

**Comment by achapiroppm** [comment]
Buenos días!
Muchas gracias por responder.
Tuvieron alguna novedad sobre el caso?
El error se sigue produciendo.

Muchas gracias

De: curcio79 ***@***.***>
Enviado el: lunes, 21 de marzo de 2022 12:30
Para: TodoPago/SDK-PHP ***@***.***>
CC: Alejandro Chapiro ***@***.***>; Mention ***@***.***>
Asunto: Re: [TodoPago/SDK-PHP] Warning: SoapClient::__doRequest(): SSL: Se ha forzado la interrupción de una conexión existente por el host remoto. (Issue #87)

No suele recibir correo electrónico de ***@***.******@***.***>. Por qué esto es importante<http://aka.ms/LearnAboutSenderIdentification>

@achapiroppm<https://github.com/achapiroppm> buenos dias, tu server donde esta desplegado?

**Comment by achapiroppm** [comment]
Buenas tardes, Mi servidor está en el hosting mochahost.com (dominio latindevs.com).
Se podría chequear también el site a donde va a correr en producción, el dominio es lanware.com.ar que reside en dreamhost.com.

**Comment by curcio79** [comment]
@achapiroppm perdon pero veo q tus prueban son en servidor local, es correcto?
C:\laragon\www\SDK-PHP\TodoPago
 veo en otra parte q me decis q esta hosteado mochahost.com, tenes el ssl activo? podria verlo online?

**Comment by achapiroppm** [comment]
Buenos días,
El SSL está activo https://latindevs.com/lanware/

Te paso una captura

***@***.***

De: curcio79 ***@***.***>
Enviado el: miércoles, 23 de marzo de 2022 15:20
Para: TodoPago/SDK-PHP ***@***.***>
CC: Alejandro Chapiro ***@***.***>; Mention ***@***.***>
Asunto: Re: [TodoPago/SDK-PHP] Warning: SoapClient::__doRequest(): SSL: Se ha forzado la interrupción de una conexión existente por el host remoto. (Issue #87)

No suele recibir correo electrónico de ***@***.******@***.***>. Por qué esto es importante<http://aka.ms/LearnAboutSenderIdentification>

@achapiroppm<https://github.com/achapiroppm> perdon pero veo q tus prueban son en servidor local, es correcto?
C:\laragon\www\SDK-PHP\TodoPago
veo en otra parte q me decis q esta hosteado mochahost.com, tenes el ssl activo? podria verlo online?

**Comment by achapiroppm** [comment]
> @achapiroppm perdon pero veo q tus prueban son en servidor local, es correcto? C:\laragon\www\SDK-PHP\TodoPago veo en otra parte q me decis q esta hosteado mochahost.com, tenes el ssl activo? podria verlo online?

Buenos dias, hice pruenas en localhost, luego de haber hecho pruebas en latindevs.com. Ahora estoy probando directamente en el dominio lanware.com.ar donde se va a desplegar el site, pero sigue produciéndose el mismo error.

**Comment by martinm1990** [comment]
Hola estoy teniendo el mismo error, ninguno de los ejemplos me funciona! Lo pudiste solucionar?

**Comment by achapiroppm** [comment]
Hola Martin! no, no tuve solución aun...

**Comment by camilo00410** [comment]
Buenas, tengo el mismo error, ya lo pudieron solucionar?

**Comment by achapiroppm** [comment]
nop...

**Comment by martinm1990** [comment]
que desastre que son!

**Comment by camilo00410** [comment]
El error es que no sirve para hacer pruebas, entonces toca hacerlo con datos reales
